#!/hint/bash
DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'git::/usr/bin/git clone --origin origin %u %o')
VCSCLIENTS=('git::git')
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -mtune=skylake -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now"
LTOFLAGS="-flto=auto"
BUILDENV=(!distcc color !ccache check !sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge debug lto)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
COMPRESSZST=(zstd -c -T0 -)
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'

